'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useRouter } from 'next/navigation';
import Image from 'next/image';

export default function ConsentPage() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [consents, setConsents] = useState({
    clinical: false,
    genetic: false,
    audit: false,
  });

  const handleConsent = (type: 'clinical' | 'genetic' | 'audit') => {
    setConsents(prev => ({ ...prev, [type]: !prev[type] }));
  };

  const handleNext = () => {
    if (step < 5) setStep(step + 1);
  };

  const handleBack = () => {
    if (step > 0) setStep(step - 1);
  };

  const handleDownloadPDF = () => {
    const date = new Date().toLocaleDateString();
    const consentText = `
BIOTEK CONSENT FORM
Generated: ${date}

DATA SHARING CONSENT
Clinical Data: ${consents.clinical ? 'CONSENTED' : 'NOT CONSENTED'}
Genetic Data: ${consents.genetic ? 'CONSENTED' : 'NOT CONSENTED'}
Audit Trail: ${consents.audit ? 'ENABLED' : 'DISABLED'}

PRIVACY GUARANTEE
- Differential Privacy Protection (ε=3.0)
- Federated Learning Architecture
- No Raw Data Sharing
- HIPAA & GDPR Compliant

PATIENT RIGHTS
- Withdraw consent anytime
- Request data deletion
- Access your data

Generated by BioTeK Platform
www.biotek.ai
    `.trim();

    const blob = new Blob([consentText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BioTeK_Consent_${date.replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleFinish = () => {
    // Store consent in localStorage
    const consentRecord = {
      timestamp: new Date().toISOString(),
      consentId: `C-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      clinical: consents.clinical,
      genetic: consents.genetic,
      audit: consents.audit,
    };
    localStorage.setItem('biotek_consent', JSON.stringify(consentRecord));
    
    // Redirect based on user role
    const session = localStorage.getItem('biotek_session');
    if (session) {
      const sessionData = JSON.parse(session);
      if (sessionData.role === 'patient') {
        router.push('/patient-dashboard');
      } else {
        router.push('/platform');
      }
    } else {
      // No session, redirect to platform
      router.push('/platform');
    }
  };

  const [aiLimitationsAcknowledged, setAiLimitationsAcknowledged] = useState(false);

  const canProceed = () => {
    if (step === 1) return aiLimitationsAcknowledged;
    if (step === 2) return consents.clinical;
    if (step === 4) return consents.audit;
    return true;
  };

  return (
    <main className="min-h-screen flex items-center justify-center px-6 py-12" style={{ backgroundColor: '#f3e7d9' }}>
      <div className="w-full max-w-2xl">
        {/* Logo */}
        <div className="flex items-center justify-center gap-3 mb-12">
          <Image 
            src="/images/ChatGPT Image Nov 10, 2025, 08_09_36 AM.png" 
            alt="BioTeK"
            width={48}
            height={48}
          />
          <span className="text-2xl font-bold">BioTeK</span>
        </div>

        <AnimatePresence mode="wait">
          {/* Step 0: Welcome */}
          {step === 0 && (
            <motion.div
              key="step0"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="bg-white/80 backdrop-blur-md rounded-3xl p-12 space-y-8"
            >
              <div className="text-center space-y-4">
                <div className="text-5xl mb-4">🧬</div>
                <h1 className="text-4xl font-bold text-black">Welcome to BioTeK</h1>
                <p className="text-lg text-black/60 max-w-xl mx-auto leading-relaxed">
                  Before accessing the platform, we need your informed consent.
                </p>
              </div>

              <div className="space-y-4 bg-black/5 rounded-2xl p-6">
                <p className="font-medium text-black">This ensures:</p>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <span className="text-xl">🔒</span>
                    <span className="text-black/70">Your data privacy is protected</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-xl">🤖</span>
                    <span className="text-black/70">You understand how AI predictions work</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-xl">🧬</span>
                    <span className="text-black/70">You control your genetic data usage</span>
                  </li>
                </ul>
              </div>

              <button
                onClick={handleNext}
                className="w-full bg-black text-white py-4 rounded-2xl font-medium hover:bg-black/80 transition-all"
              >
                Continue to Consent →
              </button>
            </motion.div>
          )}

          {/* Step 1: AI Limitations Disclosure */}
          {step === 1 && (
            <motion.div
              key="step1-ai"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="bg-white/80 backdrop-blur-md rounded-3xl p-12 space-y-8"
            >
              <div className="flex items-center justify-between mb-6">
                <span className="text-sm text-black/50">Step 1 of 4</span>
                <div className="flex gap-2">
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black/20"></div>
                  <div className="w-2 h-2 rounded-full bg-black/20"></div>
                  <div className="w-2 h-2 rounded-full bg-black/20"></div>
                </div>
              </div>

              <div className="space-y-6">
                <h2 className="text-3xl font-bold text-black">AI Limitations</h2>
                <p className="text-black/60">Important information about our AI predictions</p>
                
                <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 space-y-4">
                  <div className="flex items-center gap-2 text-amber-800 font-medium">
                    <span className="text-xl">⚠️</span>
                    <span>Please understand these limitations:</span>
                  </div>
                  <ul className="space-y-3 text-amber-900">
                    <li className="flex items-start gap-2">
                      <span className="text-amber-500 mt-1">•</span>
                      <span><strong>Not a diagnosis:</strong> AI predictions are risk estimates, not medical diagnoses. Always consult a healthcare provider.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-amber-500 mt-1">•</span>
                      <span><strong>Accuracy varies:</strong> Model performance differs across demographics. Average accuracy is ~83%.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-amber-500 mt-1">•</span>
                      <span><strong>Genetic limitations:</strong> PRS scores validated primarily on European ancestry populations.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-amber-500 mt-1">•</span>
                      <span><strong>Data dependent:</strong> Predictions rely on accurate input data and may miss factors not collected.</span>
                    </li>
                  </ul>
                </div>

                <div className="bg-blue-50 border border-blue-200 rounded-2xl p-4">
                  <a href="/ethics" target="_blank" className="flex items-center gap-2 text-blue-700 hover:text-blue-900 transition-colors">
                    <span>📋</span>
                    <span className="font-medium">View full AI Ethics & Model Cards documentation →</span>
                  </a>
                </div>

                <label className="flex items-start gap-3 p-4 rounded-xl bg-black/5 cursor-pointer hover:bg-black/10 transition-colors">
                  <input
                    type="checkbox"
                    checked={aiLimitationsAcknowledged}
                    onChange={() => setAiLimitationsAcknowledged(!aiLimitationsAcknowledged)}
                    className="mt-1 w-5 h-5 rounded border-2 border-black/20"
                  />
                  <div>
                    <div className="font-medium text-black">I understand these AI limitations</div>
                    <div className="text-sm text-black/50">(Required to continue)</div>
                  </div>
                </label>
              </div>

              <div className="flex gap-4">
                <button
                  onClick={handleBack}
                  className="flex-1 bg-white/80 text-black py-4 rounded-2xl font-medium hover:bg-white transition-all"
                >
                  ← Back
                </button>
                <button
                  onClick={handleNext}
                  disabled={!canProceed()}
                  className={`flex-1 py-4 rounded-2xl font-medium transition-all ${
                    canProceed()
                      ? 'bg-black text-white hover:bg-black/80'
                      : 'bg-black/20 text-black/40 cursor-not-allowed'
                  }`}
                >
                  Continue →
                </button>
              </div>
            </motion.div>
          )}

          {/* Step 2: Clinical Data */}
          {step === 2 && (
            <motion.div
              key="step1"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="bg-white/80 backdrop-blur-md rounded-3xl p-12 space-y-8"
            >
              <div className="flex items-center justify-between mb-6">
                <span className="text-sm text-black/50">Step 2 of 4</span>
                <div className="flex gap-2">
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black/20"></div>
                  <div className="w-2 h-2 rounded-full bg-black/20"></div>
                </div>
              </div>

              <div className="space-y-6">
                <h2 className="text-3xl font-bold text-black">Clinical Data Usage</h2>
                
                <div className="bg-black/5 rounded-2xl p-6 space-y-4">
                  <p className="font-medium text-black">We use the following clinical data:</p>
                  <p className="text-black/70">📊 Age, BMI, HbA1c, LDL, Smoking Status</p>
                </div>

                <div className="space-y-3">
                  <p className="font-medium text-black">🔒 How it's protected:</p>
                  <ul className="space-y-2 text-black/70">
                    <li>• Data stays at your hospital</li>
                    <li>• Only model updates are shared</li>
                    <li>• Encrypted in transit</li>
                  </ul>
                </div>

                <label className="flex items-start gap-3 p-4 rounded-xl bg-black/5 cursor-pointer hover:bg-black/10 transition-colors">
                  <input
                    type="checkbox"
                    checked={consents.clinical}
                    onChange={() => handleConsent('clinical')}
                    className="mt-1 w-5 h-5 rounded border-2 border-black/20"
                  />
                  <div>
                    <div className="font-medium text-black">I consent to clinical data analysis</div>
                    <div className="text-sm text-black/50">(Required to use platform)</div>
                  </div>
                </label>
              </div>

              <div className="flex gap-4">
                <button
                  onClick={handleBack}
                  className="flex-1 bg-white/80 text-black py-4 rounded-2xl font-medium hover:bg-white transition-all"
                >
                  ← Back
                </button>
                <button
                  onClick={handleNext}
                  disabled={!canProceed()}
                  className={`flex-1 py-4 rounded-2xl font-medium transition-all ${
                    canProceed()
                      ? 'bg-black text-white hover:bg-black/80'
                      : 'bg-black/20 text-black/40 cursor-not-allowed'
                  }`}
                >
                  Continue →
                </button>
              </div>
            </motion.div>
          )}

          {/* Step 3: Genetic Data */}
          {step === 3 && (
            <motion.div
              key="step2"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="bg-white/80 backdrop-blur-md rounded-3xl p-12 space-y-8"
            >
              <div className="flex items-center justify-between mb-6">
                <span className="text-sm text-black/50">Step 3 of 4</span>
                <div className="flex gap-2">
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black/20"></div>
                </div>
              </div>

              <div className="space-y-6">
                <h2 className="text-3xl font-bold text-black">Genetic Data Usage</h2>
                <p className="text-black/60">(Optional)</p>
                
                <div className="bg-black/5 rounded-2xl p-6 space-y-4">
                  <p className="font-medium text-black">🧬 Polygenic Risk Score (PRS)</p>
                  <p className="text-black/70">Including genetic data improves accuracy:</p>
                  <div className="grid grid-cols-2 gap-4 mt-4">
                    <div className="bg-white/50 rounded-xl p-4">
                      <div className="text-2xl font-bold text-black">~83%</div>
                      <div className="text-sm text-black/50">Without genetics</div>
                    </div>
                    <div className="bg-white/50 rounded-xl p-4">
                      <div className="text-2xl font-bold text-black">~88%</div>
                      <div className="text-sm text-black/50">With genetics</div>
                    </div>
                  </div>
                </div>

                <div className="space-y-3">
                  <p className="font-medium text-black">🔒 Privacy guarantees:</p>
                  <ul className="space-y-2 text-black/70">
                    <li>• Differential privacy applied</li>
                    <li>• Cannot reverse-engineer your DNA</li>
                    <li>• You can revoke consent anytime</li>
                  </ul>
                </div>

                <label className="flex items-start gap-3 p-4 rounded-xl bg-black/5 cursor-pointer hover:bg-black/10 transition-colors">
                  <input
                    type="checkbox"
                    checked={consents.genetic}
                    onChange={() => handleConsent('genetic')}
                    className="mt-1 w-5 h-5 rounded border-2 border-black/20"
                  />
                  <div>
                    <div className="font-medium text-black">I consent to genetic data analysis</div>
                    <div className="text-sm text-black/50">(Optional - you can change this later)</div>
                  </div>
                </label>
              </div>

              <div className="flex gap-4">
                <button
                  onClick={handleBack}
                  className="flex-1 bg-white/80 text-black py-4 rounded-2xl font-medium hover:bg-white transition-all"
                >
                  ← Back
                </button>
                <button
                  onClick={handleNext}
                  className="flex-1 bg-black text-white py-4 rounded-2xl font-medium hover:bg-black/80 transition-all"
                >
                  Continue →
                </button>
              </div>
            </motion.div>
          )}

          {/* Step 4: Audit & Rights */}
          {step === 4 && (
            <motion.div
              key="step3"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="bg-white/80 backdrop-blur-md rounded-3xl p-12 space-y-8"
            >
              <div className="flex items-center justify-between mb-6">
                <span className="text-sm text-black/50">Step 4 of 4</span>
                <div className="flex gap-2">
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                  <div className="w-2 h-2 rounded-full bg-black"></div>
                </div>
              </div>

              <div className="space-y-6">
                <h2 className="text-3xl font-bold text-black">Audit Trail & Data Rights</h2>
                
                <div className="bg-black/5 rounded-2xl p-6 space-y-3">
                  <p className="font-medium text-black">Every action is logged:</p>
                  <ul className="space-y-2 text-black/70">
                    <li>✓ Predictions made</li>
                    <li>✓ Data accessed</li>
                    <li>✓ Consent changes</li>
                    <li>✓ Model versions used</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <p className="font-medium text-black">Your rights:</p>
                  <ul className="space-y-2 text-black/70">
                    <li>• View all audit logs anytime</li>
                    <li>• Export your data</li>
                    <li>• Revoke consent & delete data</li>
                    <li>• Modify genetic data consent</li>
                  </ul>
                </div>

                <label className="flex items-start gap-3 p-4 rounded-xl bg-black/5 cursor-pointer hover:bg-black/10 transition-colors">
                  <input
                    type="checkbox"
                    checked={consents.audit}
                    onChange={() => handleConsent('audit')}
                    className="mt-1 w-5 h-5 rounded border-2 border-black/20"
                  />
                  <div>
                    <div className="font-medium text-black">I understand my data rights</div>
                    <div className="text-sm text-black/50">(Required)</div>
                  </div>
                </label>
              </div>

              <div className="flex gap-4">
                <button
                  onClick={handleBack}
                  className="flex-1 bg-white/80 text-black py-4 rounded-2xl font-medium hover:bg-white transition-all"
                >
                  ← Back
                </button>
                <button
                  onClick={handleNext}
                  disabled={!canProceed()}
                  className={`flex-1 py-4 rounded-2xl font-medium transition-all ${
                    canProceed()
                      ? 'bg-black text-white hover:bg-black/80'
                      : 'bg-black/20 text-black/40 cursor-not-allowed'
                  }`}
                >
                  Accept & Continue →
                </button>
              </div>
            </motion.div>
          )}

          {/* Step 5: Confirmation */}
          {step === 5 && (
            <motion.div
              key="step4"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="bg-white/80 backdrop-blur-md rounded-3xl p-12 space-y-8"
            >
              <div className="text-center space-y-4">
                <div className="text-5xl mb-4">✅</div>
                <h2 className="text-4xl font-bold text-black">Consent Recorded</h2>
              </div>

              <div className="space-y-6">
                <div className="bg-black/5 rounded-2xl p-6 space-y-3">
                  <div className="flex justify-between">
                    <span className="text-black/60">Timestamp:</span>
                    <span className="font-medium text-black">{new Date().toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-black/60">Consent ID:</span>
                    <span className="font-mono text-sm text-black">C-{Date.now()}</span>
                  </div>
                </div>

                <div className="space-y-3">
                  <p className="font-medium text-black">Your choices:</p>
                  <div className="space-y-2">
                    <div className="flex items-center gap-3 p-3 bg-white/50 rounded-xl">
                      <span className={consents.clinical ? 'text-green-600' : 'text-black/30'}>
                        {consents.clinical ? '✓' : '○'}
                      </span>
                      <span className="text-black/70">Clinical data: {consents.clinical ? 'Consented' : 'Not consented'}</span>
                    </div>
                    <div className="flex items-center gap-3 p-3 bg-white/50 rounded-xl">
                      <span className={consents.genetic ? 'text-green-600' : 'text-black/30'}>
                        {consents.genetic ? '✓' : '○'}
                      </span>
                      <span className="text-black/70">Genetic data: {consents.genetic ? 'Consented' : 'Not consented'}</span>
                    </div>
                    <div className="flex items-center gap-3 p-3 bg-white/50 rounded-xl">
                      <span className={consents.audit ? 'text-green-600' : 'text-black/30'}>
                        {consents.audit ? '✓' : '○'}
                      </span>
                      <span className="text-black/70">Audit trail: {consents.audit ? 'Enabled' : 'Disabled'}</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <button 
                  onClick={handleDownloadPDF}
                  className="w-full bg-white/80 text-black py-4 rounded-2xl font-medium hover:bg-white transition-all"
                >
                  Download Consent PDF
                </button>
                <button
                  onClick={handleFinish}
                  className="w-full bg-black text-white py-4 rounded-2xl font-medium hover:bg-black/80 transition-all"
                >
                  Enter Dashboard →
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </main>
  );
}
